import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  mails: [
    {
      id: 1,
      fromName: "Alice Johnson",
      fromEmail: "alice.johnson.com",
      toName: "Bob Smith",
      toEmail: "bob.smith.com",
      cc: null,
      bcc: null,
      threadId: 1,
      messageId: "<message1.com>",
      inReplyTo: null,
      references: null,
      subject: "Meeting Reminder",
      body: "<p>Hi Bob,</p><p>This is a reminder for our meeting tomorrow.</p><p>Best,<br/>Alice</p>",
      isRead: false,
      folder: "INBOX",
      uid: 101,
      sentAt: "2024-08-12T10:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-12T10:00:00.000Z",
      updatedAt: "2024-08-12T10:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 2,
      fromName: "Bob Smith",
      fromEmail: "bob.smith.com",
      toName: "Alice Johnson",
      toEmail: "alice.johnson.com",
      cc: null,
      bcc: null,
      threadId: 1,
      messageId: "<message2.com>",
      inReplyTo: "<message1.com>",
      references: "<message1.com>",
      subject: "Re: Meeting Reminder",
      body: "<p>Hi Alice,</p><p>Thanks for the reminder. Looking forward to it.</p><p>Best,<br/>Bob</p>",
      isRead: true,
      folder: "INBOX",
      uid: 102,
      sentAt: "2024-08-12T11:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-12T11:00:00.000Z",
      updatedAt: "2024-08-12T11:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 3,
      fromName: "Charlie Brown",
      fromEmail: "charlie.brown.com",
      toName: "Diana Prince",
      toEmail: "diana.prince.com",
      cc: null,
      bcc: null,
      threadId: 2,
      messageId: "<message3.com>",
      inReplyTo: null,
      references: null,
      subject: "Project Update",
      body: "<p>Hi Diana,</p><p>Here's the latest update on the project.</p><p>Regards,<br/>Charlie</p>",
      isRead: false,
      folder: "INBOX",
      uid: 103,
      sentAt: "2024-08-13T09:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-13T09:00:00.000Z",
      updatedAt: "2024-08-13T09:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 4,
      fromName: "Diana Prince",
      fromEmail: "diana.prince.com",
      toName: "Charlie Brown",
      toEmail: "charlie.brown.com",
      cc: null,
      bcc: null,
      threadId: 2,
      messageId: "<message4.com>",
      inReplyTo: "<message3.com>",
      references: "<message3.com>",
      subject: "Re: Project Update",
      body: "<p>Hi Charlie,</p><p>Thank you for the update. Everything looks good.</p><p>Best,<br/>Diana</p>",
      isRead: true,
      folder: "INBOX",
      uid: 104,
      sentAt: "2024-08-13T10:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-13T10:00:00.000Z",
      updatedAt: "2024-08-13T10:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 5,
      fromName: "Emily Clark",
      fromEmail: "emily.clark.com",
      toName: "Frank Wright",
      toEmail: "frank.wright.com",
      cc: null,
      bcc: null,
      threadId: 3,
      messageId: "<message5.com>",
      inReplyTo: null,
      references: null,
      subject: "Feedback Request",
      body: "<p>Hi Frank,</p><p>I would like your feedback on the recent changes.</p><p>Thanks,<br/>Emily</p>",
      isRead: false,
      folder: "INBOX",
      uid: 105,
      sentAt: "2024-08-14T08:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-14T08:00:00.000Z",
      updatedAt: "2024-08-14T08:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 6,
      fromName: "Frank Wright",
      fromEmail: "frank.wright.com",
      toName: "Emily Clark",
      toEmail: "emily.clark.com",
      cc: null,
      bcc: null,
      threadId: 3,
      messageId: "<message6.com>",
      inReplyTo: "<message5.com>",
      references: "<message5.com>",
      subject: "Re: Feedback Request",
      body: "<p>Hi Emily,</p><p>I'll get back to you with my feedback soon.</p><p>Best,<br/>Frank</p>",
      isRead: true,
      folder: "INBOX",
      uid: 106,
      sentAt: "2024-08-14T09:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-14T09:00:00.000Z",
      updatedAt: "2024-08-14T09:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 7,
      fromName: "Grace Lee",
      fromEmail: "grace.lee.com",
      toName: "Henry Adams",
      toEmail: "henry.adams.com",
      cc: null,
      bcc: null,
      threadId: 4,
      messageId: "<message7.com>",
      inReplyTo: null,
      references: null,
      subject: "Invoice for Services",
      body: "<p>Hi Henry,</p><p>Please find the attached invoice for the services rendered.</p><p>Best,<br/>Grace</p>",
      isRead: false,
      folder: "INBOX",
      uid: 107,
      sentAt: "2024-08-15T07:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-15T07:00:00.000Z",
      updatedAt: "2024-08-15T07:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 8,
      fromName: "Henry Adams",
      fromEmail: "henry.adams.com",
      toName: "Grace Lee",
      toEmail: "grace.lee.com",
      cc: null,
      bcc: null,
      threadId: 4,
      messageId: "<message8.com>",
      inReplyTo: "<message7.com>",
      references: "<message7.com>",
      subject: "Re: Invoice for Services",
      body: "<p>Hi Grace,</p><p>Thank you for the invoice. I will review it.</p><p>Best,<br/>Henry</p>",
      isRead: true,
      folder: "INBOX",
      uid: 108,
      sentAt: "2024-08-15T08:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-15T08:00:00.000Z",
      updatedAt: "2024-08-15T08:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 9,
      fromName: "Ivy Martinez",
      fromEmail: "ivy.martinez.com",
      toName: "Jack Wilson",
      toEmail: "jack.wilson.com",
      cc: null,
      bcc: null,
      threadId: 5,
      messageId: "<message9.com>",
      inReplyTo: null,
      references: null,
      subject: "Team Meeting Agenda",
      body: "<p>Hi Jack,</p><p>Here is the agenda for our team meeting next week.</p><p>Best,<br/>Ivy</p>",
      isRead: false,
      folder: "INBOX",
      uid: 109,
      sentAt: "2024-08-16T06:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-16T06:00:00.000Z",
      updatedAt: "2024-08-16T06:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 10,
      fromName: "Jack Wilson",
      fromEmail: "jack.wilson.com",
      toName: "Ivy Martinez",
      toEmail: "ivy.martinez.com",
      cc: null,
      bcc: null,
      threadId: 5,
      messageId: "<message10.com>",
      inReplyTo: "<message9.com>",
      references: "<message9.com>",
      subject: "Re: Team Meeting Agenda",
      body: "<p>Hi Ivy,</p><p>Thank you for sending the agenda.</p><p>Best,<br/>Jack</p>",
      isRead: true,
      folder: "INBOX",
      uid: 110,
      sentAt: "2024-08-16T07:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-16T07:00:00.000Z",
      updatedAt: "2024-08-16T07:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 11,
      fromName: "Karen Davis",
      fromEmail: "karen.davis.com",
      toName: "Leon Harris",
      toEmail: "leon.harris.com",
      cc: null,
      bcc: null,
      threadId: 6,
      messageId: "<message11.com>",
      inReplyTo: null,
      references: null,
      subject: "Contract Review",
      body: "<p>Hi Leon,</p><p>Please review the attached contract.</p><p>Best,<br/>Karen</p>",
      isRead: false,
      folder: "INBOX",
      uid: 111,
      sentAt: "2024-08-17T05:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-17T05:00:00.000Z",
      updatedAt: "2024-08-17T05:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 12,
      fromName: "Leon Harris",
      fromEmail: "leon.harris.com",
      toName: "Karen Davis",
      toEmail: "karen.davis.com",
      cc: null,
      bcc: null,
      threadId: 6,
      messageId: "<message12.com>",
      inReplyTo: "<message11.com>",
      references: "<message11.com>",
      subject: "Re: Contract Review",
      body: "<p>Hi Karen,</p><p>I've reviewed the contract and have some comments.</p><p>Best,<br/>Leon</p>",
      isRead: true,
      folder: "INBOX",
      uid: 112,
      sentAt: "2024-08-17T06:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-17T06:00:00.000Z",
      updatedAt: "2024-08-17T06:00:00.000Z",
      deletedAt: null,
    },
    {
      id: 13,
      fromName: "Mia Williams",
      fromEmail: "mia.williams.com",
      toName: "Nate Brown",
      toEmail: "nate.brown.com",
      cc: null,
      bcc: null,
      threadId: 7,
      messageId: "<message13.com>",
      inReplyTo: null,
      references: null,
      subject: "Event Invitation",
      body: "<p>Hi Nate,</p><p>You are invited to our annual event.</p><p>Regards,<br/>Mia</p>",
      isRead: false,
      folder: "INBOX",
      uid: 113,
      sentAt: "2024-08-18T04:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-18T04:00:00.000Z",
      updatedAt: "2024-08-18T04:00:00.000Z",
      deletedAt: null,
    },
  ],

  selectedThread: [
    {
      id: 13,
      fromName: "Mia Williams",
      fromEmail: "mia.williams.com",
      toName: "Nate Brown",
      toEmail: "nate.brown.com",
      cc: null,
      bcc: null,
      threadId: 7,
      messageId: "<message13.com>",
      inReplyTo: null,
      references: null,
      subject: "Event Invitation",
      body: "<p>Hi Nate,</p><p>You are invited to our annual event.</p><p>Regards,<br/>Mia</p>",
      isRead: false,
      folder: "INBOX",
      uid: 113,
      sentAt: "2024-08-18T04:00:00.000Z",
      archivedAt: null,
      createdAt: "2024-08-18T04:00:00.000Z",
      updatedAt: "2024-08-18T04:00:00.000Z",
      deletedAt: null,
    },
  ],
};

const mailSlice = createSlice({
  name: "mail",
  initialState,
  reducers: {
    setSelectedThread: (state, action) => {
      state.selectedThread = action.payload;
    },
    pushIntoSelectedThread: (state, action) => {
      state.selectedThread.push(action.payload);
    },
    deleteMail: (state, action) => {
      const { id } = action.payload;

      // Check if the mail with the given id exists
      const mailExists = state.mails.some((mail) => mail.id === id);

      if (mailExists) {
        // Remove the mail from the mails array
        state.mails = state.mails.filter((mail) => mail.id !== id);

        // Clear the selectedThread
        state.selectedThread = [];
      }
    },
  },
});

export const { setSelectedThread, pushIntoSelectedThread, deleteMail } =
  mailSlice.actions;

export default mailSlice.reducer;
